#!/bin/bash

exec qemu-system-x86_64 -machine "q35,kernel-irqchip=split,memory-backend=mem0" \
  -bios /usr/share/ovmf/OVMF.fd \
  -accel kvm -cpu host \
  -smp 4 \
  -object memory-backend-ram,id=mem0,size=10G \
  -drive cache=writeback,file=image.img,id=drive1,if=none,index=1,werror=report \
  -device virtio-blk-pci,bootindex=1,drive=drive1,serial=root \
  -kernel image.vmlinuz -initrd image.initrd \
  -append "$(cat image.cmdline)" \
  -virtfs local,path=./spec,mount_tag=spec,security_model=mapped,readonly=on \
  -net nic,netdev=user.0,model=virtio -netdev user,id=user.0,hostfwd=tcp::10023-:22 \
  -nographic
